apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: fierce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo.fierce.svc.cluster.local
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: fierce
spec:
  selector:
    app: mongo-express
  ports:
  - port: 80
    targetPort: 8081
